### ISSUE TITLE
Empty pages shown in graph view, return 404

### ISSUE THREAD

**Issue by adamBacso** [adamBacso/hive#10]
Similar results as #3 , but probably another fix is needed. Disable nonexistent pages??

**Comment by adamBacso** [comment]
working on a fix

**Comment by adamBacso** [comment]
New pages created from text do not include any metadata, but are shown. Solution seems to be a template that populates page with a preset based on the parent page.

**Comment by gergooo** [comment]
https://github.com/jackyzha0/quartz/issues/112

**Comment by adamBacso** [comment]
Possible template used for new file creation (obsidian specific). Instead of selecting text and pressing `[` twice, set [Templater](https://github.com/SilentVoid13/Templater) hotkey to something (mine is bound to `ctrl+L`) and use that. Sadly this is only an Obsidian workaround, but the concept could be applied elsewhere as well.

[_template_new-page (example).md](https://github.com/adamBacso/hive/files/10368099/_template_new-page.example.md)
