### ISSUE TITLE
Dataview queries don't render properly

### ISSUE THREAD

**Issue by adamBacso** [adamBacso/hive#11]
### Current behavior
Only the query code is shown. ([Example - Verbs.md](https://github.com/adamBacso/hive/files/10368559/Verbs.md))

### Expected behavior
List of pages (verbs in this case) to be shown.

### Possible fixes
Convert query result to markdown

**Comment by gergooo** [comment]
https://github.com/blacksmithgu/obsidian-dataview/issues/40

**Comment by adamBacso** [comment]
dataviewjs can produce markdown results
